config/routes.rb
Rails.application.routes.draw do

  get 'lecture/:id' => 'lecture#info'

  get 'professor/:id' => 'professor#info'

  devise_for :users, :controllers => {:registrations => 'user/registrations'}
  resources :courses

  resources :evaluations
  root 'evaluations#index'

  get 'sessions/login' => 'sessions#login'
  get 'sessions/test' => 'sessions#test'

  post 'sessions/auth' => 'sessions#auth'

  post 'courses/search' =>'courses#search'
  post 'users/favorites_delete' => 'users#favorites_delete'
  post 'users/favorites_add' => 'users#favorites_add'
  get 'users/index' => 'users#index'
  post 'courses/favorites_delete' => 'courses#favorites_delete'
  post 'courses/favorites_add' => 'courses#favorites_add'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/evaluation.rb
class Evaluation < ApplicationRecord
  belongs_to :course
  belongs_to :user

  def set_user!(user)
    self.user_id = user.id
    self.save!
  end

end

app/controllers/evaluations_controller.rb
class EvaluationsController < ApplicationController
  def index
    @evaluations = Evaluation.all
    
  end
  before_action :authenticate_user!

  def new
    @evaluation = Evaluation.new
    @courses = Course.all
    @lectures = Lecture.all
    @professors = Professor.all
  end

  def create
    @user = current_user
    prof = evaluation_params[:professor]
    lec = evaluation_params[:lecture]
    evaluation = Evaluation.new(evaluation_params)
    evaluation.set_user!(@user)
    if evaluation.save!
      redirect_to "/"
    else
      redirect_back(fallback_location: root_path)
    end
  end

  private
  def evaluation_params
    params.require(:evaluation).permit(:user_id, :course_id, :point, :content, :professor_id, :lecture_id)
  end
end

app/helpers/evaluations_helper.rb
module EvaluationsHelper
end

app/views/evaluations/index.html.erb
<div class="container">


<% @evaluations.each do |e| %>
    <a href="/courses/<%= e.course.id %>">이동</a>
    <%= e.user.email %>
    <%= e.course.lecture.name %>
    <%= e.course.professor.name %>
    <%= e.point %>
    <%= e.content %>
    <% if current_user %>
        <% if Favorite.exists?(course_id: e.id, user_id: current_user.id) %>
            <%= button_to '관심 강의에서 제거', users_favorites_delete_path(u_id: current_user, c_id: e.id),
                          method: :post, :onClick => 'alert("관심강의에서 제거되었습니다!")', class: 'waves-effect waves-light btn' %>
        <% else %>
            <%= button_to '관심 강의에 추가', users_favorites_add_path(u_id: current_user, c_id: e.id),
                          method: :post, :onClick => 'alert("관심강의에 추가되었습니다!")', class: 'waves-effect waves-light btn'%>
        <% end %>
    <% end %>
    <hr>

<% end %>
</div>

app/views/evaluations/new.html.erb
<script>
  $( function() {
      $("#tags").autocomplete({
          source: $('#tags').data('autocomplete-source'),
          select: function(event, ui) {
              event.preventDefault();
               $(this).val(ui.item.label);
              $('#course_id').val(ui.item.value);
          }
      })
  })
</script>
<br>
<div class="container">

<%= form_for @evaluation, class: "ui-widget" do |f| %>

    <%= f.text_field :course_id, id: "tags", placeholder: "lecture(professor)", data: {autocomplete_source: @courses.map{ |t| {:label => t.lecture.name + "(" + t.professor.name + ")", value: t.id}}}%> <br>
    <%= f.hidden_field :course_id, id: "course_id" %>
    <%= f.hidden_field :user_id, id: "user_id", value: current_user.id %>
    <%= f.number_field :point, placeholder:"point" %> <br>
    <%= f.text_field :content, placeholder:"content" %> <br>
                        <%= button_tag(type: "submit", class: "btn waves-effect waves-light z-depth-3") do %>
                    평가 완료하기 <i class="material-icons left">send</i>
                    <% end %> <br>

<% end %>

</div>