config/routes.rb
Rails.application.routes.draw do

  get 'lecture/:id' => 'lecture#info'

  get 'professor/:id' => 'professor#info'

  devise_for :users, :controllers => {:registrations => 'user/registrations'}
  resources :courses

  resources :evaluations
  root 'evaluations#index'

  get 'sessions/login' => 'sessions#login'
  get 'sessions/test' => 'sessions#test'

  post 'sessions/auth' => 'sessions#auth'

  post 'courses/search' =>'courses#search'
  post 'users/favorites_delete' => 'users#favorites_delete'
  post 'users/favorites_add' => 'users#favorites_add'
  get 'users/index' => 'users#index'
  post 'courses/favorites_delete' => 'courses#favorites_delete'
  post 'courses/favorites_add' => 'courses#favorites_add'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Minerva</title>
  <link rel="icon" href="/assets/owl.png">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <style>
    body {
      font-family: "Quicksand", sans-serif;
      display: flex;
      min-height: 100vh;
      flex-direction: column;
    }

    main {
      flex: 1 0 auto;
    }

    footer.page-footer {
      background-color: #9ccc65;
    }

    .navb {
        box-shadow: 0 0 10px 0 rgba(0, 0, 0, 0.19), 0 0 10px 0 rgba(0, 0, 0, 0.19);
    }
    
    nav {
        background-color: #212121;
    }
  </style>
  <script>
    $(document).ready(function() {
      $(".dropdown-button").dropdown();
    });
</script>
  </head>

  <body>

  <div class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container">
      <div class="navbar-brand">
        <%= link_to 'Minerva', evaluations_path, class: 'navbar-brand brand-logo' %>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="navbar-nav mr-auto">
          <li><%= link_to '과목 목록', courses_path, class: "nav-item nav-link" %></li>
          <% if current_user %>
            <li><%= link_to '새 평가', new_evaluation_path, class: "nav-item nav-link" %></li>
          <% end %>
        </ul>
        <ul class="navbar-nav ml-auto">
          <% if current_user %>
            <li><%= link_to current_user.email, users_index_path, class: "nav-item nav-link" %></li>
            <li><%= link_to '로그아웃', destroy_user_session_path, class: "nav-item nav-link", :method => 'delete' %></li>
          <% else %>
            <li><%= link_to '로그인', new_user_session_path, class: "nav-item nav-link" %></li>
            <li><%= link_to '회원가입', new_user_registration_path, class: "nav-item nav-link" %></li>
          <% end %>
        </ul>
      </div>

    </div>
  </div>
<!--
<nav class="navb">
  <div class="navb-wrapper">
    <div class="container">
    <a href=<%= evaluations_path %> class="brand-logo">Minerva</a>
    <ul class="right hide-on-med-and-down">
            <li><a href=<%= courses_path %>>과목 목록</a></li>
        <% if current_user %>
              <li><a href=<%= new_evaluation_path %>>새 평가</a></li>
  <li><a class="dropdown-button" href="#!" data-activates="dropdown1"><%= current_user.email %><i class="material-icons right">arrow_drop_down</i></a></li>
    <% else %>
            <li><a href=<%= new_user_registration_path %>>회원가입</a></li>
            <li><a href=<%= new_user_session_path %>>로그인</a></li>
        <% end %>
    </ul>
  </div>
  </div>
</nav>
-->
  <div class="container">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>">
        <%= value %>
      </div>
    <% end %>

  </div>

  <%= yield %>
<!--
  <div id="footer">
    <p class="text-muted">Created by LIKELION X KOREATECH</p>
  </div>
-->
  </body>
</html>